$(document).ready(function(){
  $("#btnfirst").click(function(){
    $("#main1").fadeToggle();
  });
  $("#btnsecond").click(function(){
    $("#main2").fadeToggle();
  });
  $("#btnthird").click(function(){
    $("#main3").fadeToggle();
  });
  $("#btnfourth").click(function(){
    $("#main4").fadeToggle();
  });
  $("#btnfifth").click(function(){
    $("#main5").fadeToggle();
  });
});
